### ISSUE TITLE
Crashes after restarting game

### ISSUE THREAD

**Issue by xhixzi** [YoYoGames/GMEXT-Steamworks#100]
I'm using the Steamworks extension in my GameMaker project, but when I relaunch the game using game_restart(); it crashes. Very odd issue, not sure why it is occurring

IDE v2024.8.1.171  Runtime v2024.8.1.218

**Comment by stuckie** [comment]
Could you use the in-IDE bug reporter when this happens, so that we can get the compile log and securely receive the project for further testing?

I'm going to close this specific issue, as we don't have the information required to action it.

Thanks.

**Comment by DiasFranciscoA** [comment]
@xhixzi To use it with game restart please refer to the demo provided in the extensions.

> [!IMPORTANT] Using `game_restart` is a bad practice and although being part of the functions available at runtime we advise not to use it. This advise applies specially if you are using extensions. Keep that in mind.
