### ISSUE TITLE
[FEATURE REQUEST] Steam Timelines

### ISSUE THREAD

**Issue by shichen85** [YoYoGames/GMEXT-Steamworks#103]
Steam just released their new Timelines feature, which allows developers to fire in-game events that will be captured by Steam's video recording feature: https://partner.steamgames.com/doc/features/timeline

This feature can allow both developers and players to easily capture interesting gameplay footages to share for QA or marketing purposes.

**Comment by DiasFranciscoA** [comment]
Hey there @shichen85, is this the feature that you are you mentioning?

https://github.com/YoYoGames/GMEXT-Steamworks/wiki/timeline

**Comment by shichen85** [comment]
Yes. Apologies for not checking the latest version here. Closing the issue now.
