### ISSUE TITLE
Steamworks Extension: [Feature Request] Update to support Steamworks SDK v1.61

### ISSUE THREAD

**Issue by Emc1923** [YoYoGames/GMEXT-Steamworks#106]
Investigate updating the extension to support the most recent version of Steamworks SDK (v1.61): https://partner.steamgames.com/downloads/list

**Comment by DiasFranciscoA** [comment]
Support for SDK v1.61 was added to the main branch.

> [!IMPORTANT]
> This will be a breaking change, meaning using the extension with previous versions of the SDK will just not work and will crash execution. This update will only be available in `v2.1.0` of Steamworks (to be released soon)
