### ISSUE TITLE
Steamworks initializing for developer accounts but only small subset of players

### ISSUE THREAD

**Issue by turdjabroni** [YoYoGames/GMEXT-Steamworks#107]
I released a game using this extension in September, and our Windows users have been broadly unable to trigger achievements and access workshop content. We have tried using earlier versions and recently updated to the most recent version to no effect. The issue seems to not be present on Mac, but, of course, the user sample size there is much smaller. I modified the version we are using to include functions for accessing and setting metadata for UGC and added them to the YY file. However, that the Steam API initialization works from both the editor and the Steam build for developers and Mac users makes me think the issue lies elsewhere. 

We have also tried changing the sandboxing settings, as our early issues with API initialization on Mac were resolved by correcting the sandbox settings, but that does not seem to have had an effect on Windows. We initially did not have stats and achievements enabled on the Steamworks dashboard, but resolving that only fixed the issue for a small subset of users.

Is there something in the Steam_Init process that could be broken by the addition of metadata get/set functions? I couldn't find anything in the Steamworks API documentation indicating that there would be a difference between the query enable functions for long descriptions etc. and returning metadata information, but I am sure that you all are more familiar with the API than I am.

I am going to try pushing a build to the beta branch with the default version of the extension to see if that resolves it. Is there something that could go wrong during the compilation of a modified version of the extension that would break initialization for non-developers? That a user being a developer consistently prevents the problem makes me think that the issue could be a permissions thing on the API side, but the small group of users (with as of yet no discernable pattern) for whom the API initializes successfully pokes a hole in that theory.

As an aside, if this issue can be resolved with the UGC metadata functions intact I would love to submit them (with documentation) for future releases. When they work they are quite handy for sifting through UGC via an in-game browser.

**Comment by turdjabroni** [comment]
Using the default version of the extension resolved the issue. Is there a known issue with the steam_api metadata functions that prevented their inclusion from previous releases? Apologies if this is a previously covered problem; I could not find reference to it in the documentation or in previous issues.

**Comment by DiasFranciscoA** [comment]
Hello @turdjabroni,

We are currently looking at your ticket and we're afraid we don't quite understand what the problem is. What is the "default version", what meta data functions are you talking about? I mean what is the API functions that you are trying to use? What is the documentation link for them? Is this something you add yourself to the original extension?

Thank you in advance for your cooperation,
Francisco Dias

**Comment by turdjabroni** [comment]
Sorry for the lack of clarity. By default version I'm referring to the unmodified version of the most recent release of the extension. Switching to this version that does not contain my additions resolves the API connection problem.

The meta data functions I am referring to are [SteamUGC:SetItemMetadata](https://partner.steamgames.com/doc/api/ISteamUGC#SetItemMetadata) and [SteamUGC:SetReturnMetadata](https://partner.steamgames.com/doc/api/ISteamUGC#SetReturnMetadata). I added these to steam_ugc.cpp. I also put in some code to attach the metadata to the ds_map returned by the function OnUGCQueryResult. 

The added functions work perfectly when launching the game from the Editor, and in the Mac build on Steam, but not in the Steam build on Windows for most users. Their inclusion causes most Windows builds of the game to fail to connect to the Steam API, for reasons that continue to puzzle me. Below are screenshots of my modifications within the steam_ugc.cpp file.

![Image](https://github.com/user-attachments/assets/7785e653-95fb-4f20-a075-827ef8ca01dc)
![Image](https://github.com/user-attachments/assets/fc21ef00-071b-46b1-a86d-57db2202a0ff)
![Image](https://github.com/user-attachments/assets/72eab371-7b8e-4f78-ab28-135ab04562d8)

I'm happy to upload my modified version of the source code somewhere if that would be helpful. This has been a challenging issue to debug, since I have been unable to find a way to access the extension's debug information from the Steam releases, yet that is the only environment in which I can replicate the issue. Please let me know if there is anything else that I can clarify, and thank you very much for the prompt attention!

**Comment by DiasFranciscoA** [comment]
So we went ahead and added the requested features to the official extension.
This won't be release until next stable (next week) but keep an eye on that.

Regarding your issue you will need to build the dll as **Release** is you do a Debug build it will only work for people with VS installed in their systems and I can probably guess that's what happened.

Thank you for reaching out once again,
Francisco Dias

**Comment by turdjabroni** [comment]
Ahhh, that explains the breakdown of Windows users who were connecting correctly. Thank you very much! I appreciate it greatly; you all do excellent work.

**Comment by YYBartT** [comment]
Added documentation for the two new functions and updated the wiki with the changes ([UGC reference](https://github.com/YoYoGames/GMEXT-Steamworks/wiki/ugc)).
