### ISSUE TITLE
Crashes when game folder contains Unicode characters

### ISSUE THREAD

**Issue by nixxquality** [YoYoGames/GMEXT-Steamworks#108]
The game [ADEN](https://store.steampowered.com/app/2152740/ADEN/) recently released on Steam, but it's crashing for users.
I wanted to investigate, so I pulled a recent version of the Steamworks extension from here. It was crashing in a different way with the latest version.

![2024-12-13_10-25-46](https://github.com/user-attachments/assets/295202ff-5c0d-400d-a5b8-5bfb55e1f5f6)

The game folder has Japanese characters in it, so it's pretty easy to understand how this happened.

![2024-12-13_10-26-22](https://github.com/user-attachments/assets/6b73a010-2d98-4353-85ec-98a1df7630cf)

The [DesktopExtensionTools_getPathToExe function](https://github.com/YoYoGames/GMEXT-Steamworks/blob/94f1ba2dc6a6a9b148c7b9bbdd5d645a9b722652/source/Steamworks_gml/extensions/steamworks/steamworks_cpp/DesktopExtensionTools.cpp#L10) converts the path to a string, before it later gets [converted to a path again](https://github.com/YoYoGames/GMEXT-Steamworks/blob/94f1ba2dc6a6a9b148c7b9bbdd5d645a9b722652/source/Steamworks_gml/extensions/steamworks/steamworks_cpp/GMLSteam/steam_init_new.cpp#L66). This conversion step crashes.
If you just use current_path directly, it doesn't crash.

[I was about to submit a pull request to fix this](https://github.com/nixxquality/GMEXT-Steamworks/commit/f421ef3fea5979a86c58b89175f503d5a71ab6a4), but I see the function is used in the macOS version, so I'm not sure how it should be fixed now.
Maybe if both functions return an std::filesystem::path and the macOS function does the string -> path conversion in there? I don't know if that's available in Objective-C.

**Comment by DiasFranciscoA** [comment]
This should be fixed in lastest update of the extension (will release soon) also note that the new update will required Steamworks SDK v1.61
