### ISSUE TITLE
macOS blocks Dylib files

### ISSUE THREAD

**Issue by CelaldoganGunes** [YoYoGames/GMEXT-Steamworks#13]
Hello.
Every time I press F5 and run my game on my MacBook Air m2, OS blocks game and gives warning about dylib file of this extension. I have to allow it from OS security settings every time I run the game. How can I get rid of these warnings automatically?

**Comment by DiasFranciscoA** [comment]
Hello,

Which dylib does the OS complains about? the steamworks extension on or the lib_steam.dylib one?
Can you confirm the target you are compiling to? macOS VM or YYC?

Please note that VM is not supported anymore.

**Comment by CelaldoganGunes** [comment]
"libsteam_api.dylib" is the file I have problem with. I downloaded main branch and copied extension files from there to my game's directory. (Steam Auth function is only in that version, you know.)

The target is macOS VM, but how is it not supported anymore? Do I have to use macOS YYC?

<img width="1266" alt="image" src="https://user-images.githubusercontent.com/17123945/223148282-c8493755-59e8-46e9-9962-636afbc077a1.png">

**Comment by DiasFranciscoA** [comment]
On macOS you will need to use YYC, Apple requires the use of signed dylibs and when compiling to YYC dylibs are automatically signed avoiding those issues.

Yes, macOS VM is not supported by this extension.

**Comment by DiasFranciscoA** [comment]
Please file a bug on that "Help -> Report a bug" from the IDE. This is a problem with the building/running process that is not related with the extension whatsoever.

**Comment by CelaldoganGunes** [comment]
I will, thank you.
