### ISSUE TITLE
Regression/reoccurrence: Some users are not initalizing steam correctly (Possibly related to visual studio install)

### ISSUE THREAD

**Issue by L-Clouds** [YoYoGames/GMEXT-Steamworks#15]
I think this has reoccurred with 1.3.0 - players with Visual Studio installed are having steam initialize, and players who have only the redist are not.

_Originally posted by @L-Clouds in https://github.com/YoYoGames/GMEXT-Steamworks/issues/10#issuecomment-1483990929_
            
Rolling back to 1.2.3 fixed it.

**Comment by DiasFranciscoA** [comment]
Solved with v1.3.1 (Hotfix)
