### ISSUE TITLE
Macos YYM can not initialize SteamWorks 1.4.1

### ISSUE THREAD

**Issue by CelaldoganGunes** [YoYoGames/GMEXT-Steamworks#17]
GameMaker version:
<img width="367" alt="image" src="https://user-images.githubusercontent.com/17123945/229254657-41203cd6-0cec-45ef-9162-a9261dd3426a.png">

This happens on 1.4.X and the previous one, but doesn't happen on 1.2.2. (Downloaded them from github)
Also, when I create .app file, it has the same problem.

I created an empty project, imported the extension from marketplace (version 1.4.1).
A test object has "steam_update()" in its step event and the object is in the room.

"
if (steam_initialised() == true)
{
	draw_text(36,36,"steam is enabled")
}
else
{
	draw_text(36,3,"steam problem")
}
"
this code writes "steam problem" on the screen.

.sh files give some errors and do not forget to search (CTRL F) "liblibSteamworks.dylib"
Also CTRL F this:
"/Users/celal/Desktop/project_name_test/extensions/Steamworks/post_build_step.sh: line 54: optionGetValue: command not found"
I write these errors because log file is 200 and more pages long. This way you can easily find errors.
It is too long and Github doesn't allow to me paste it here, so I uploaded it to Google Docs.
https://docs.google.com/document/d/1G8Xw7kBZWPu8XUq80eff1Xl_nCWH7Y-JoDAldh2BDRs/edit?usp=sharing

**Comment by DiasFranciscoA** [comment]
It's happening due to line endings being CRLF instead of LF if you want a quick fix, open the scriptUtils.sh file in Visual Studio Code (for example) and in the bottom right corner change line formatting from CRLF to LF and save. This should solve your issue. We will be fixing this on next update.

Thank you,
Francisco Dias

**Comment by CelaldoganGunes** [comment]
Thank you. It fixed the problem.
