### ISSUE TITLE
The Way to Allow Mac VM to run the extension.

### ISSUE THREAD

**Issue by CelaldoganGunes** [YoYoGames/GMEXT-Steamworks#18]
I am using Steamworks 1.2.2 as it is the last version that doesn't block Mac VM to run the game.

--------------------------------------------------------
<img width="694" alt="image" src="https://user-images.githubusercontent.com/17123945/229251685-e9a6cb1b-4455-4fdf-8c0d-44c230565c45.png">
--------------------------------------------------------

By this way, I can run the game without any security error while developing it.
Maybe you can allow Mac VM for development purposes and block it when trying to create an executable.
Why Mac VM?
It is faster to run the game.

**Comment by DiasFranciscoA** [comment]
We will handle this in future updates, disabling Gatekeeper is not an alternative since it is unsafe.
