### ISSUE TITLE
not work here 

### ISSUE THREAD

**Issue by cJether** [YoYoGames/GMEXT-Steamworks#20]
All of them not work here! could you help me plz?

**Comment by DiasFranciscoA** [comment]
Hello @cJether,

Thank you for reaching out to us with your post. In order to provide you with further assistance, we kindly request the following information:

* Demo Game: Is the issue occurring with the demo game we provide? Please let us know if you are experiencing the problem specifically with the demo game or with your custom project.

* IDE/Runner Version: Could you please provide us with the version of the IDE/Runner you are currently using? This information will help us better understand the environment in which the issue is occurring.

* Target Platform: Are you compiling the game for Windows or macOS? Knowing the target platform will help us in narrowing down the potential causes of the issue.

* Output Log: To diagnose the issue accurately, we would greatly appreciate it if you could share the output log from the IDE. Please ensure that any personal or sensitive data is properly hidden or redacted before sharing the log.

* Extension Version: Lastly, could you inform us about the version of the extension you are currently using? Knowing the specific version will aid us in identifying any potential compatibility issues.

Providing the above information is crucial for us to assist you effectively. We appreciate your cooperation in sharing these details.

If you have any additional questions or concerns, please don't hesitate to let us know. We are here to help you.

**Comment by cJether** [comment]
Demo Game: the demo game work here.

but I cannot test steam achievements with this demo game.

My Game: I cannot unlock a steam achivement in my own game.


IDE/Runner Version: 



Target Platform: Windows 11


Output Log:&nbsp; see the attachment




Jether
***@***.***



&nbsp;






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "YoYoGames/GMEXT-Steamworks"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年6月21日(星期三) 晚上7:20
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [YoYoGames/GMEXT-Steamworks] not work here  (Issue #20)





 
Hello @cJether,
 
Thank you for reaching out to us with your post. In order to provide you with further assistance, we kindly request the following information:
  
 
Demo Game: Is the issue occurring with the demo game we provide? Please let us know if you are experiencing the problem specifically with the demo game or with your custom project.
 
 
 
IDE/Runner Version: Could you please provide us with the version of the IDE/Runner you are currently using? This information will help us better understand the environment in which the issue is occurring.
 
 
 
Target Platform: Are you compiling the game for Windows or macOS? Knowing the target platform will help us in narrowing down the potential causes of the issue.
 
 
 
Output Log: To diagnose the issue accurately, we would greatly appreciate it if you could share the output log from the IDE. Please ensure that any personal or sensitive data is properly hidden or redacted before sharing the log.
 
 
 
Extension Version: Lastly, could you inform us about the version of the extension you are currently using? Knowing the specific version will aid us in identifying any potential compatibility issues.
 
  
Providing the above information is crucial for us to assist you effectively. We appreciate your cooperation in sharing these details.
 
If you have any additional questions or concerns, please don't hesitate to let us know. We are here to help you.

**Comment by DiasFranciscoA** [comment]
Hello,

Thank you for providing the additional information. However, we noticed that there are no attachments included in your response. To assist you further, we kindly request that you provide the missing information:

IDE/Runner Version: Could you please inform us of the version of the IDE/Runner you are currently using? This information is crucial for understanding the environment in which the issue is occurring and providing accurate guidance.

Output Log: We would greatly appreciate it if you could share the output log from the IDE. This log will assist us in diagnosing the issue more accurately. Please ensure that any personal or sensitive data is properly hidden or redacted before sharing the log.

Regarding the demo game, we would like to clarify that it is primarily intended to demonstrate the functionality of the extensions. We do not provide support for the misuse or customization of the extensions in the demo project. It is important to use the default extension options when testing the demo project (with the exception of the SDK location path).

For your own game, specifically regarding unlocking Steam achievements, please ensure that you are utilizing the appropriate extension options and following the required integration steps outlined in the documentation. Additionally, make sure that you have the Steamworks SDK v1.55 installed and configured correctly.

Once we receive the missing information, we will be able to offer more targeted assistance to help resolve the issue you are experiencing.

Thank you for your cooperation, and we look forward to hearing back from you.

Best regards,

Francisco Dias

**Comment by cJether** [comment]
2023.4.0.84
2023.4.0.113



Jether
***@***.***



&nbsp;






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "YoYoGames/GMEXT-Steamworks"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年6月23日(星期五) 下午4:53
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [YoYoGames/GMEXT-Steamworks] not work here  (Issue #20)





 
Hello,
 
Thank you for providing the additional information. However, we noticed that there are no attachments included in your response. To assist you further, we kindly request that you provide the missing information:
 
IDE/Runner Version: Could you please inform us of the version of the IDE/Runner you are currently using? This information is crucial for understanding the environment in which the issue is occurring and providing accurate guidance.
 
Output Log: We would greatly appreciate it if you could share the output log from the IDE. This log will assist us in diagnosing the issue more accurately. Please ensure that any personal or sensitive data is properly hidden or redacted before sharing the log.
 
Regarding the demo game, we would like to clarify that it is primarily intended to demonstrate the functionality of the extensions. We do not provide support for the misuse or customization of the extensions in the demo project. It is important to use the default extension options when testing the demo project (with the exception of the SDK location path).
 
For your own game, specifically regarding unlocking Steam achievements, please ensure that you are utilizing the appropriate extension options and following the required integration steps outlined in the documentation. Additionally, make sure that you have the Steamworks SDK v1.55 installed and configured correctly.
 
Once we receive the missing information, we will be able to offer more targeted assistance to help resolve the issue you are experiencing.
 
Thank you for your cooperation, and we look forward to hearing back from you.
 
Best regards,
 
Francisco Dias

**Comment by DiasFranciscoA** [comment]
Thank you for providing the additional information regarding the IDE and runtime version. However, we kindly request that you attach the output log directly here on GitHub instead of answering via email. This will ensure that the attachments are properly received and accessible for our review and analysis. Attaching the output log directly in the GitHub conversation will enable us to more effectively diagnose the issue you are experiencing.

We appreciate your cooperation and understanding. If you have any further questions or need assistance, please don't hesitate to let us know.

Best regards,

Francisco Dias

**Comment by cJether** [comment]
"C:\ProgramData/GameMakerStudio2/Cache/runtimes\runtime-2023.4.0.113/bin/igor/windows/x64/Igor.exe"  -j=8  -options="C:\Users\Jethe\AppData\Local\GameMakerStudio2\GMS2TEMP\build.bff" -v -- Windows Run Loaded Macros from C:\Users\Jethe\AppData\Roaming\GameMakerStudio2\Cache\GMS2CACHE\ProtectThe_E6AE57A_92A4A889\macros.json Options: C:\ProgramData/GameMakerStudio2/Cache/runtimes\runtime-2023.4.0.113\bin\platform_setting_defaults.json Options: C:\Users\Jethe\AppData\Roaming/GameMakerStudio2\215826544_1854844\local_settings.json Options: C:\Users\Jethe\AppData\Roaming\GameMakerStudio2\Cache\GMS2CACHE\ProtectThe_E6AE57A_92A4A889\targetoptions.json Setting up the Asset compiler C:\ProgramData/GameMakerStudio2/Cache/runtimes\runtime-2023.4.0.113/bin/assetcompiler/windows/x64/GMAssetCompiler.dll  /c /mv=1 /zpex /iv=0 /rv=0 /bv=0 /j=8  /gn="ProtectThePlanet" /td="C:\Users\Jethe\AppData\Local\GameMakerStudio2\GMS2TEMP" /cd="C:\Users\Jethe\AppData\Roaming\GameMakerStudio2\Cache\GMS2CACHE\ProtectThe_E6AE57A_92A4A889" /rtp="C:\ProgramData/GameMakerStudio2/Cache/runtimes\runtime-2023.4.0.113" /zpuf="C:\Users\Jethe\AppData\Roaming/GameMakerStudio2\215826544_1854844"  /ffe="d3t+fjZrf25zeTdwgjZ8eXZ2bGttdTZ5em98a3GCN4ODbTZzeH5vdnZzfW94fW82eH92dnN9cjZ2eXFzeGl9fXk2fm99fjZtf31+eXdpb3iANnBzdn41cII=" /m=windows /tgt=64 /nodnd /cfg="Default" /o="C:\Users\Jethe\AppData\Local\GameMakerStudio2\GMS2TEMP\ProtectThePlanet_592618B_VM" /sh=True /optionsini="C:\Users\Jethe\AppData\Local\GameMakerStudio2\GMS2TEMP\ProtectThePlanet_592618B_VM\options.ini"  /cvm /baseproject="C:\ProgramData/GameMakerStudio2/Cache/runtimes\runtime-2023.4.0.113\BaseProject\BaseProject.yyp" "E:\GMS2_ProtectThePlanet\ProtectThePlanet \ProtectThePlanet.yyp" /preprocess="C:\Users\Jethe\AppData\Roaming\GameMakerStudio2\Cache\GMS2CACHE\ProtectThe_E6AE57A_92A4A889" Found Project Format 2 +++ FAST SERIALISATION SUCCESSFUL LOAD AND LINK TIME  (with worker concurrency 8): 380.1734ms Loaded Project: ProtectThePlanet finished. Found Project Format 2 +++ FAST SERIALISATION SUCCESSFUL LOAD AND LINK TIME  (with worker concurrency 8): 71.4812ms Loaded Project: __yy_sdf_shader finished. Found Project Format 2 C:/ProgramData/GameMakerStudio2/Cache/runtimes/runtime-2023.4.0.113/bin/ParticlePresets/GMPresetParticles/particlelib/GM_Warp_Lines/GM_Warp_Lines.yy: C:/ProgramData/GameMakerStudio2/Cache/runtimes/runtime-2023.4.0.113/bin/ParticlePresets/GMPresetParticles/particlelib/GM_Warp_Lines/GM_Warp_Lines.yy(59,2): GMSC Error: Field 'spriteAnimate' missing in YoYoStudio.Resources.GMPSEmitter. +++ ORIGINAL SERIALISATION SUCCESSFUL LOAD AND LINK TIME: 155.0733ms Loaded Project: GMPresetParticles finished. Release build Options: C:\Users\Jethe\AppData\Roaming\GameMakerStudio2\Cache\GMS2CACHE\ProtectThe_E6AE57A_92A4A889\ExtensionOptions.json OptionsIni Options: C:\Users\Jethe\AppData\Roaming\GameMakerStudio2\Cache\GMS2CACHE\ProtectThe_E6AE57A_92A4A889\PlatformOptions.json [Compile] Run asset compiler C:\ProgramData/GameMakerStudio2/Cache/runtimes\runtime-2023.4.0.113/bin/assetcompiler/windows/x64/GMAssetCompiler.dll  /c /mv=1 /zpex /iv=0 /rv=0 /bv=0 /j=8  /gn="ProtectThePlanet" /td="C:\Users\Jethe\AppData\Local\GameMakerStudio2\GMS2TEMP" /cd="C:\Users\Jethe\AppData\Roaming\GameMakerStudio2\Cache\GMS2CACHE\ProtectThe_E6AE57A_92A4A889" /rtp="C:\ProgramData/GameMakerStudio2/Cache/runtimes\runtime-2023.4.0.113" /zpuf="C:\Users\Jethe\AppData\Roaming/GameMakerStudio2\215826544_1854844"  /ffe="d3t+fjZrf25zeTdwgjZ8eXZ2bGttdTZ5em98a3GCN4ODbTZzeH5vdnZzfW94fW82eH92dnN9cjZ2eXFzeGl9fXk2fm99fjZtf31+eXdpb3iANnBzdn41cII=" /m=windows /tgt=64 /nodnd /cfg="Default" /o="C:\Users\Jethe\AppData\Local\GameMakerStudio2\GMS2TEMP\ProtectThePlanet_592618B_VM" /sh=True /optionsini="C:\Users\Jethe\AppData\Local\GameMakerStudio2\GMS2TEMP\ProtectThePlanet_592618B_VM\options.ini"  /cvm /baseproject="C:\ProgramData/GameMakerStudio2/Cache/runtimes\runtime-2023.4.0.113\BaseProject\BaseProject.yyp" "E:\GMS2_ProtectThePlanet\ProtectThePlanet \ProtectThePlanet.yyp" /debug /bt=run /rt=vm /64bitgame=true Looking for built-in fallback image in C:\ProgramData/GameMakerStudio2/Cache/runtimes\runtime-2023.4.0.113\bin\BuiltinImages Compile Constants...finished. Remove DnD...finished. Compile Scripts...finished. Compile Rooms...finished. Compile Objects...finished. Compile Timelines...finished. Compile Triggers...finished. Compile Extensions...finished. Global scripts...finished. finished. collapsing enums. Final Compile...finished. Saving IFF file... C:\Users\Jethe\AppData\Local\GameMakerStudio2\GMS2TEMP\ProtectThePlanet_592618B_VM\ProtectThePlanet.win Writing Chunk... GEN8 size ... -0.00 MB option_game_speed=60 Writing Chunk... OPTN size ... 0.00 MB Writing Chunk... LANG size ... 0.00 MB Writing Chunk... EXTN size ... 0.00 MB Writing Chunk... SOND size ... 0.01 MB Writing Chunk... AGRP size ... 0.00 MB Writing Chunk... SPRT size ... 0.00 MB Writing Chunk... BGND size ... 0.01 MB Writing Chunk... PATH size ... 0.00 MB Writing Chunk... SCPT size ... 0.00 MB Writing Chunk... GLOB size ... 0.00 MB Writing Chunk... SHDR size ... 0.00 MB Writing Chunk... FONT size ... 0.00 MB Writing Chunk... TMLN size ... 0.00 MB Writing Chunk... OBJT size ... 0.00 MB Writing Chunk... FEDS size ... 0.01 MB Writing Chunk... ACRV size ... 0.00 MB Writing Chunk... SEQN size ... 0.00 MB Writing Chunk... TAGS size ... 0.00 MB Writing Chunk... ROOM size ... 0.00 MB Writing Chunk... DAFL size ... 0.00 MB Writing Chunk... EMBI size ... 0.00 MB Writing Chunk... PSEM size ... 0.00 MB Writing Chunk... PSYS size ... 0.00 MB Writing Chunk... TPAGE size ... 0.00 MB Texture Group - __YY__0fallbacktexture.png_YYG_AUTO_GEN_TEX_GROUP_NAME_ Texture Group - Default Writing Chunk... TGIN size ... 0.00 MB Writing Chunk... CODE size ... 0.00 MB Writing Chunk... VARI size ... 0.01 MB Writing Chunk... FUNC size ... 0.00 MB Writing Chunk... FEAT size ... 0.00 MB Writing Chunk... STRG size ... 0.00 MB Writing Chunk... TXTR size ... 0.03 MB 0 Compressing texture... writing texture __YY__0fallbacktexture.png_YYG_AUTO_GEN_TEX_GROUP_NAME__0.yytex...  1 Compressing texture... writing texture Default_0.yytex...  2 Compressing texture... writing texture Default_1.yytex...  E:\GMS2_ProtectThePlanet\ProtectThePlanet\extensions\Steamworks\iOSSource\..\post_textures.bat Writing Chunk... AUDO size ... 2.48 MB Writing Chunk... SCPT size ... -0.00 MB Writing Chunk... DBGI size ... 0.00 MB Writing Chunk... INST size ... 0.01 MB Writing Chunk... LOCL size ... 0.00 MB Writing Chunk... DFNC size ... 0.00 MB Writing Chunk... STRG size ... 0.00 MB Stats : GMA : Elapsed=702.049 Stats : GMA : sp=53,au=2,bk=0,pt=0,sc=0,sh=1,fo=1,tl=0,ob=24,ro=2,da=0,ex=1,ma=25,fm=0xB00048E42820 Options: C:\Users\Jethe\AppData\Roaming\GameMakerStudio2\Cache\GMS2CACHE\ProtectThe_E6AE57A_92A4A889\MainOptions.json Options: C:\Users\Jethe\AppData\Roaming\GameMakerStudio2\Cache\GMS2CACHE\ProtectThe_E6AE57A_92A4A889\macros.json Options: C:\Users\Jethe\AppData\Roaming\GameMakerStudio2\Cache\GMS2CACHE\ProtectThe_E6AE57A_92A4A889\preferences.json E:\GMS2_ProtectThePlanet\ProtectThePlanet\extensions\Steamworks\post_build_step.bat  [STEAMWORKS] INIT: Script initialization succeeded (v1.4.3 :: 1). "Copying Windows (64 bit) dependencies"     Ŀ¼: C:\Users\Jethe\AppData\Local\GameMakerStudio2\GMS2TEMP Mode                 LastWriteTime         Length Name                                                                  ----                 -------------         ------ ----                                                                  d-----         2023/6/23     16:30                ProtectThePlanet_592618B_VM                                           E:\GMS2_ProtectThePlanet\ProtectThePlanet\extensions\Steamworks\post_build_step.bat DONE (0) Igor complete. [Run] Run game C:\ProgramData/GameMakerStudio2/Cache/runtimes\runtime-2023.4.0.113/windows/x64/Runner.exe  -game "C:\Users\Jethe\AppData\Local\GameMakerStudio2\GMS2TEMP\ProtectThePlanet_592618B_VM\ProtectThePlanet.win" Setting scheduler resolution to 1 [STEAMWORKS]: Debug: Writing AppID 2425160 to file C:\Users\Jethe\AppData\Local\GameMakerStudio2\GMS2TEMP\ProtectThePlanet_592618B_VM\steam_appid.txt [STEAMWORKS]: Debug: Wrote AppID without errors. Setting breakpad minidump AppID = 585410 SteamInternal_SetMinidumpSteamID:  Caching Steam ID:  76561198436353479 [API loaded no] [STEAMWORKS]: SteamAPI_Init had succeeded without errors, debug flag = 1 YYExtensionInitialise CONFIGURED   Ok, you can continue SteamUser()-&gt;BLoggedOn()Attempting to set gamepadcount to 12 DirectX11: Using hardware device Couldn't set app to fullscreen as it's occluded by something. Will try again later... Collision Event time(microsecs)=4 Variable_Global_Init() PrepareGame() Audio_Init() Game_Prepare() Script_Prepare()  TimeLine_Prepare()  Object_Prepare()  Room_Prepare()  Finished PrepareGame()  Run_Start Done g_EffectsManager.Init() Done RenderStateManager CreateColPairs took 0.000000s 18 usecs for 25 object types obj_col_numb=0 physobjcount=1 resizes 0 final size 1 Done ObjectLists Done Extension_Initialize About to startroom Total memory used = 12401375 (0x00bd3adf) bytes 11.83MB Free memory = 5995520 (0x005b7c00) bytes 5.72MB Peak memory used = 10760908 (0x00a432cc) bytes 10.26MB **********************************. Entering main loop. **********************************. Trying to reset display as we're not in fullscreen Trying to reset display as we're not in fullscreen Resizing swap chain... Resizing swap chain... Resizing window...steamapi  0 steamapi  0 ###game_end###0 Attempting to set gamepadcount to 0 Script_Free called with 0 and global 0 Unsetting previous scheduler resolution of 1 C:\ProgramData/GameMakerStudio2/Cache/runtimes\runtime-2023.4.0.113/windows/x64/Runner.exe DONE (0) Igor complete. elapsed time 00:00:19.9467923s for command "C:\ProgramData/GameMakerStudio2/Cache/runtimes\runtime-2023.4.0.113/bin/igor/windows/x64/Igor.exe" -j=8  -options="C:\Users\Jethe\AppData\Local\GameMakerStudio2\GMS2TEMP\build.bff" -v -- Windows Run started at 06/23/2023 16:30:13 SUCCESS: Run Program Complete



Jether
***@***.***



&nbsp;






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "YoYoGames/GMEXT-Steamworks"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年6月23日(星期五) 下午5:03
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [YoYoGames/GMEXT-Steamworks] not work here  (Issue #20)





 
Thank you for providing the additional information regarding the IDE and runtime version. However, we kindly request that you attach the output log directly here on GitHub instead of answering via email. This will ensure that the attachments are properly received and accessible for our review and analysis. Attaching the output log directly in the GitHub conversation will enable us to more effectively diagnose the issue you are experiencing.
 
We appreciate your cooperation and understanding. If you have any further questions or need assistance, please don't hesitate to let us know.
 
Best regards,
 
Francisco Dias

**Comment by DiasFranciscoA** [comment]
Thank you for providing the output log. Upon reviewing the log, everything appears to be in order. In order to assist you further, we kindly request that you submit the project you are currently using to our helpdesk. Once you have submitted the project, please provide us with the ticket number here so that we can easily link it to our ongoing discussion. We will then follow up with you through the helpdesk ticket to provide the necessary assistance.

Please note that we can only offer support for issues related to the demo project. As per our policy, we do not provide support for custom projects utilizing the extension.

Thank you for your understanding. We look forward to receiving your project through the helpdesk and assisting you further.

Best regards,

Francisco Dias

**Comment by cJether** [comment]
[ProtectThePlanet.zip](https://github.com/YoYoGames/GMEXT-Steamworks/files/11847279/ProtectThePlanet.zip)

**Comment by DiasFranciscoA** [comment]
Please be aware that this is a public repository, and sharing your project and log information here may expose them to the public. To ensure the security and confidentiality of your project, we highly recommend that you create a HelpDesk ticket through our [contact page](https://accounts.yoyogames.com/contact-us). By submitting your project through the HelpDesk ticket system, we can guarantee the privacy of your information and provide a more secure and appropriate channel for discussing sensitive details.

In the HelpDesk ticket, we may require additional information to better understand and address the issue you are facing. Rest assured that any confidential or private information shared through the HelpDesk ticket system will be handled securely and only used for the purpose of assisting you with the specific issue.

Thank you for your understanding and cooperation. Please proceed to the HelpDesk ticket system to file your project, and once you have done so, kindly provide us with the ticket number here for reference.

Best regards,

Francisco Dias

**Comment by cJether** [comment]
ticket number is: (#210272)



Jether
***@***.***



&nbsp;






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "YoYoGames/GMEXT-Steamworks"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年6月23日(星期五) 晚上6:48
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [YoYoGames/GMEXT-Steamworks] not work here  (Issue #20)





 
Please be aware that this is a public repository, and sharing your project and log information here may expose them to the public. To ensure the security and confidentiality of your project, we highly recommend that you create a HelpDesk ticket through our contact page. By submitting your project through the HelpDesk ticket system, we can guarantee the privacy of your information and provide a more secure and appropriate channel for discussing sensitive details.
 
In the HelpDesk ticket, we may require additional information to better understand and address the issue you are facing. Rest assured that any confidential or private information shared through the HelpDesk ticket system will be handled securely and only used for the purpose of assisting you with the specific issue.
 
Thank you for your understanding and cooperation. Please proceed to the HelpDesk ticket system to file your project, and once you have done so, kindly provide us with the ticket number here for reference.
 
Best regards,
 
Francisco Dias
