### ISSUE TITLE
[NOT A BUG] Long compiling time - copying dependencies is something that is required on every build.

### ISSUE THREAD

**Issue by SuperHebbe** [YoYoGames/GMEXT-Steamworks#26]
Hi

After I started to use the Steamwork sversion from github it takes 30 seconds longer each time I compile my game.
Here are the 3 lines it does on every compile.

V:\_GMS\IB\extensions\Steamworks\post_build_step.bat 
[STEAMWORKS] INIT: Script initialization succeeded (v1.5.0 :: 1).
"Copying Windows (64 bit) dependencies"

YoYo support couldn't help me and send me here.

Hope this will be sorted out very soon as of now it's too slow to continue working on my game.

Thanks :)

**Comment by CelaldoganGunes** [comment]
I have this problem, too.
Windows or MacOS, it doesn't matter. The extension takes too much time

**Comment by DiasFranciscoA** [comment]
This cannot be avoided and the extension scripts need to be initialized and the dependencies need to be copied on every execution. The dependencies are not copied into your project but to the output folder and so it needs to be copied everytime.
There is no proper solution for this, thought it seems odd that no other user seems to be having this problem. We would request you to open an helpdesk ticket and attach your yyz project so we can locally test this. Also send an image of your extension configuration options as well as complete output log copy (please go into the extension panel and set log level to 2)

**Comment by DiasFranciscoA** [comment]
@CelaldoganGunes @SuperHebbe could you please specify the setup your are using? Is the project or the SDK path in a disk with slow access? This setup would result in slowdowns while copying the files over. On our side the overhead doesn't reach half a second.

**Comment by SuperHebbe** [comment]
@DiasFranciscoA Hi, I have my SDK path on a SSD hard drive.
I also timed the time it took to copy files, and it takes 26 seconds each time I compile. This problem started when the steamworks add on was moved to github.

If it helps I can give you TeamViewer access.

![image](https://github.com/YoYoGames/GMEXT-Steamworks/assets/9902807/643f1699-04d9-4ccc-af4f-bf7b657bd296)

**Comment by DiasFranciscoA** [comment]
This behavior isn't indicative of a bug. Comparing the integration time of Steamworks when it was embedded in the runner to its current state as an extension might not be apples-to-apples, given that the extension now necessitates copying over dependencies. However, a 30-second increase in compile time seems unusual. @SuperHebbe, could you clarify if are those specifics line that are causing the compile/build to stall for this duration? Or is the entire process taking an extra 30 seconds? Additionally, have you observed a 30-second reduction in compile time when you deactivate the extension?
