### ISSUE TITLE
[ISSUE] "Failure to generate hash" error on Mac, scriptUtils.sh errors

### ISSUE THREAD

**Issue by CDSHeadDev** [YoYoGames/GMEXT-Steamworks#27]
Current OS: Monterey 1.2.6
Runtime version: 4.0.113

Options: /Users/**MYNAME**/Library/Application Support/GameMakerStudio2/
Cache/GMS2CACHE/**GAME NAME**_11875855_6ED587D0/MainOptions.json
Options: /Users/**MYNAME**/Library/Application Support/GameMakerStudio2/
Cache/GMS2CACHE/**GAME NAME**_11875855_6ED587D0/macros.json
Options: /Users/**MYNAME**/Library/Application Support/GameMakerStudio2/
Cache/GMS2CACHE/**GAME NAME**_11875855_6ED587D0/preferences.json
bash -l -c "! [[ -x '/Users/**MYNAME**/GameMakerStudio2/**GAMENAME**/
extensions/Steamworks/post_build_step.sh' ]] && chmod +x '/Users/**MYNAME**/
GameMakerStudio2/**GAMENAME**/extensions/Steamworks/
post_build_step.sh'; exit 0"
bash DONE (0)
bash -l -c "[[ $(file '/Users/**MYNAME**/GameMakerStudio2/**GAMENAME**/
extensions/Steamworks/post_build_step.sh') == *CRLF* ]] && sed -i -e 's/\r$//' '/
Users/**MYNAME**/GameMakerStudio2/**GAMENAME**/extensions/
Steamworks/post_build_step.sh'; exit 0"
bash DONE (0)
/Users/**MYNAME**/GameMakerStudio2/**GAMENAME**/extensions/
Steamworks/post_build_step.sh
/Users/**MYNAME**/GameMakerStudio2/**GAMENAME**/extensions/
Steamworks/scriptUtils.sh: line 79: GOLD2/extensions/Steamworks/
post_build_step.sh=GameMakerStudio2: No such file or directory
/Users/**MYNAME**/GameMakerStudio2/**GAMENAME**/extensions/
Steamworks/scriptUtils.sh: line 65: =LOG_LABEL: command not found
[UNSET] INIT: Script initialization succeeded (v0.0.0 :: 2).
[UNSET] INFO: Accessed extension option 'versionStable' with value ''.
[UNSET] INFO: Accessed extension option 'versionBeta' with value ''.
[UNSET] INFO: Accessed extension option 'versionDev' with value ''.
[UNSET] INFO: Accessed extension option 'versionLTS' with value ''.
[UNSET] INFO: Accessed extension option 'sdkHashWin' with value ''.
[UNSET] INFO: Accessed extension option 'sdkHashMac' with value ''.
[UNSET] INFO: Accessed extension option 'sdkHashLinux' with value ''.
[UNSET] INFO: Accessed extension option 'sdkPath' with value ''.
[UNSET] INFO: Accessed extension option 'sdkVersion' with value ''.
[UNSET] INFO: Accessed extension option 'debug' with value ''.
[UNSET] INFO: Extracted part 1 of version '2023.4.0.113' with value '2023'.
[UNSET] INFO: Extracted part 2 of version '2023.4.0.113' with value '4'.
/Users/**MYNAME**/GameMakerStudio2/**GAMENAME**/extensions/
Steamworks/scriptUtils.sh: line 296: [: : integer expression expected
/Users/**MYNAME**/GameMakerStudio2/**GAMENAME**/extensions/
Steamworks/scriptUtils.sh: line 299: [: : integer expression expected
/Users/**MYNAME**/GameMakerStudio2/**GAMENAME**/extensions/
Steamworks/scriptUtils.sh: line 296: [: : integer expression expected
/Users/**MYNAME**/GameMakerStudio2/**GAMENAME**/extensions/
Steamworks/scriptUtils.sh: line 299: [: : integer expression expected
/Users/**MYNAME**/GameMakerStudio2/**GAMENAME**/extensions/
Steamworks/scriptUtils.sh: line 296: [: : integer expression expected
/Users/**MYNAME**/GameMakerStudio2/**GAMENAME**/extensions/
Steamworks/scriptUtils.sh: line 299: [: : integer expression expected
/Users/**MYNAME**/GameMakerStudio2/**GAMENAME**/extensions/
Steamworks/scriptUtils.sh: line 296: [: : integer expression expected
/Users/**MYNAME**/GameMakerStudio2/**GAMENAME**/extensions/
Steamworks/scriptUtils.sh: line 299: [: : integer expression expected
[UNSET] INFO: Compared version '2023.4.0.113' with version ''.
[UNSET] INFO: Asserted that version '2023.4.0.113' is greater than or equal to
version ''.
[UNSET] INFO: Version lock check passed successfully, with version
'2023.4.0.113'.
[UNSET] INFO: Resolved path into '/Users/**MYNAME**/GameMakerStudio2/
**GAMENAME**'.
[UNSET] ERROR: Failed to generate hash for '/Users/**MYNAME**/
GameMakerStudio2/**GAME NAME**' does not exist or is not a file.
/Users/**MYNAME**/GameMakerStudio2/**GAMENAME**/extensions/
Steamworks/post_build_step.sh exited with non-zero status (1)
elapsed time 00:01:11.9050870s for command "/Users/Shared/
GameMakerStudio2/Cache/runtimes/runtime-2023.4.0.113/bin/igor/osx/x64/
Igor" -j=8 -options="/tmp/GameMakerStudio2/GMS2TEMP/build.bff" -v -- Mac
PackageZip started at 08/13/2023 21:41:54
FAILED: Package Program Complete
For the details of why this build failed, please review the whole log above and
also see your Compile Errors window.

At my wits end trying to figure this out. Set it up exactly as noted in the new documentation provided here for version 1.55 (the PDF included is still for version 1.53). I added the path for the SDK and app numbers. I've been able to build on a native Windows computer and build to a Linux virtual machine with this latest version, but trying to build remotely to the Mac or build on the Mac hasn't worked.

**Comment by DiasFranciscoA** [comment]
This as been fixed in last commit to the main branch and will soon be updated on both github releases and marketplace.

Regarding the documentation we are in the process of moving it to a new system, and it will get updated then.
