### ISSUE TITLE
[DOCUMENTATION] Wrong title in Social API

### ISSUE THREAD

**Issue by k0T0z** [YoYoGames/GMEXT-Steamworks#32]
This [title](https://github.com/YoYoGames/GMEXT-Steamworks/wiki/Social#steam_set_rich_presence-1) is wrong.

**Comment by DiasFranciscoA** [comment]
Fixed

**Comment by k0T0z** [comment]
Cool

**Comment by k0T0z** [comment]
@DiasFranciscoA Please update this as well, The first two functions are the same one of them must be ``steam_clear_rich_presence``.

![image](https://github.com/YoYoGames/GMEXT-Steamworks/assets/74428638/587b0f67-eb73-4d8d-bfcf-9f3c876ee6a1)
