### ISSUE TITLE
[DOCUMENTATION] Add the event type "lobby_chat_update" to docs

### ISSUE THREAD

**Issue by RoyallGuards** [YoYoGames/GMEXT-Steamworks#36]
In the current document, we still don't have anything about the event type "lobby_chat_update", it is an event that is triggered in Async-Steam, when someone enters or leaves the lobby, with a field called "changed_flags", if it is 1, it indicates that someone entered the lobby, case 2, someone left the lobby, and the steam_id of the player who entered/left the lobby appears.
```gml
{
     event_type : "lobby_chat_update", 
     lobby_id : xxx 
     change_flags : 1, //1 for new connection on lobby and 2 for disconnec
     user_id : xxx, ///the id of the user that joined or left the lobby
     change_id : xxx ///the id that have "changed", the same as user_id
}
```

**Comment by YYBartT** [comment]
This is now added to the JSDoc in the source repo and the wiki has been updated with the new contents.
