### ISSUE TITLE
Built Game does not run, steam reports 'launching' then stops

### ISSUE THREAD

**Issue by Fun0rama** [YoYoGames/GMEXT-Steamworks#43]
I have imported the GMEXT-Steamworks plugin into my project and downloaded the steamworks version 1.55 the project will run find in the editor, but when I try to build and launch it won't open.

Some things to note, I am using an app id of 480 for development, I do not know if a unique app id is required. I have mapped the sdk to the proper location in the files. The built version does have the steamworks.dll in the build. Steam reports application launching, hangs there, then stops reporting launching and quits.

**Comment by jackerley** [comment]
I think you will need to use your own app id, otherwise it is trying to launch this app from Steam
