### ISSUE TITLE
steamworks on macOS doesn't work when playtesting on gamemaker

### ISSUE THREAD

**Issue by Vikinglock** [YoYoGames/GMEXT-Steamworks#45]
I don’t know if this is intentional but when using the steamworks extension on windows and running my game directly from gamemaker, it opens as if it were opened in steam with the steam overlay working and notifying friends. When I open the same game on macos, it opens as if I had never installed the steamworks extension in the first place.

**Comment by Vikinglock** [comment]
I have looked through the output, and it seems like Gamemaker is looking for "liblibSteamworks.dylib" which I assume could be a typo, and it is looking for "usr/lib/libsteam_api.dylib" (I do not have writing permissions in "usr/lib").

**Comment by stuckie** [comment]
Do you get the same issues when using a packaged build?

**Comment by Vikinglock** [comment]
this is one part of the error that I get when playtesting
```
error trying to load /(directory to my game)/GM_MAC/The_Game/The_Game.app/Contents/Resources/libsteamworks.dylib - dlopen(/(directory to my game)/GM_MAC/The_Game/The_Game.app/Contents/Resources/libsteamworks.dylib, 0x0001): Library not loaded: @loader_path/libsteam_api.dylib
  Referenced from: <7AA8C2F4-41FD-317B-B761-23AB3082559D> /(directory to my game)/GM_MAC/The_Game/The_Game.app/Contents/Resources/libsteamworks.dylib
  Reason: tried: '/(directory to my game)/GM_MAC/The_Game/The_Game.app/Contents/Resources/libsteam_api.dylib' (), '/usr/local/lib/libsteam_api.dylib' (), '/usr/lib/libsteam_api.dylib' (no such file, not in dyld cache)
```

**Comment by DiasFranciscoA** [comment]
So it's only the overlay that doesn't work? Everything else works, that is a known problem. You can see the overlay when running on macOS, the extension and all its features will still work as expected.

**Comment by Vikinglock** [comment]
I'm not sure if anything else works since I haven't done much yet with steamworks but the achievements don't work, the overlay doesn't work, and even when I uploaded a beta to steam, the multiplayer would not work

**Comment by DiasFranciscoA** [comment]
I would need to know some information on your project before I can give you better assistance.

* What IDE are you using? 
* Do you have the extension options configured (double click the extension)?
* What Runner version are you using?
* Are you compiling for VM or YYC (extensions are not compatible with macOS VM)

To further help in the debug process we would also need the log file (console output) please go into the extension options, set the `Log Level` to 2 and run your game.

Thank you in advance

**Comment by Vikinglock** [comment]
I think it works now because I made a lobby and the player lags behind a bit
I was using IDE version 2023.8.2.108 and I just updated to 2023.11.0.121 so this could be why
I did have the extension options configured correctly
I can't remember what runner version I was using
and the game wouldn't run if it was vm

**Comment by Vikinglock** [comment]
Thank you all
It works now and all I needed to do was just update the IDE to the latest version although still I don't know why it didn't work in any of the previous versions
