### ISSUE TITLE
More of a question than issue

### ISSUE THREAD

**Issue by georgecrhennen** [YoYoGames/GMEXT-Steamworks#46]
I am looking to have a better guide on the steam networking for this. I have a pretty applicable game. I would even be willing to open source my Steam game that uses this for various features as a teaching tool if I could get networking done right with Steam.

Please add me on discord: gigastructure.

**Comment by stuckie** [comment]
What in particular are you needing support with?

**Comment by georgecrhennen** [comment]
Just confused, and have no idea how to use or get started with doing steam multiplayer.

**Comment by stuckie** [comment]
We will look to improve our multiplayer demo at some point in the future.

**Comment by georgecrhennen** [comment]
I am trying to do something now, as in make something with this. You wouldnt need to make a demo if you helped me make one, or at least directed the information in the right direction. Right now it's just.. stuff.
