### ISSUE TITLE
Game fails to run with Steamworks Ext when setting up Constrained Language Mode

### ISSUE THREAD

**Issue by owlyzz** [YoYoGames/GMEXT-Steamworks#50]
Hey there,

The game (even a new empty project, on LTS or 2023.x) fails to run with the Seamworks Ext, generating this error:

Cannot invoke method. Method invocation is supported only on core types in this language mode.
At line:1 char:94
+ ...  $basePath; $ExecutionContext.SessionState.Path.GetUnresolvedProvider ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : MethodInvocationNotSupportedInConstrainedLanguage
 
[STEAMWORKS] ERROR: Path '' does not exist.

--------------------------------------------------------------------------------------------------------------------------------------

The cause: setting up constrained language mode with an environment variable. Basically if you do what ThioJoe suggests you do here at 2:24 will cause the crash, and the only workaround is to then delete that environment variable: 

https://www.youtube.com/watch?v=zW69MisrsWk

All the best, 
Owly

**Comment by DiasFranciscoA** [comment]
@owlyzz 

This problem will require the user to disable restricted mode, by running the command:
```ps
Set-ExecutionPolicy RemoteSigned -Scope CurrentUser
```
This is a requirement for all our extension that make use of scriptUtils (this is the case of Steamworks)
A proper error message (+ instructions) will be added to next release of the extension.

**Comment by DiasFranciscoA** [comment]
fixed in 1.6.0 github release
