### ISSUE TITLE
missing the function "steam_file_get_list"

### ISSUE THREAD

**Issue by Reverend-Greg** [YoYoGames/GMEXT-Steamworks#56]
I'm testing the steamworks extension (Steamworks.Ext.v1.5.1). According to the docs the function ["steam_file_get_list"](https://github.com/YoYoGames/GMEXT-Steamworks/wiki/cloud#steam_file_get_list) returns a list of all currently stored files in the user's cloud storage.
However the function doesn't seem to be in the extension. The code editor can't find it and when I check the function list in the extensions dll, that function is not listed.

![grafik](https://github.com/YoYoGames/GMEXT-Steamworks/assets/76689475/9c892a40-4c17-4a3e-a986-f6a48a338a26)

**Comment by DiasFranciscoA** [comment]
This function was implemented in 1.6.0 now available as a release in github
