### ISSUE TITLE
steam_set_achievement is not working

### ISSUE THREAD

**Issue by kt-altyn** [YoYoGames/GMEXT-Steamworks#57]
![image](https://github.com/YoYoGames/GMEXT-Steamworks/assets/92668715/c737c8ad-2df7-4642-bd5c-15818ab8ce60)
i have set up an achievements via my steamworks panel, released it publicly. i set up steamworks ext 1.5.0 correctly, set up my app id and official steam sdk 1.55 location. however this code does not works.
![image](https://github.com/YoYoGames/GMEXT-Steamworks/assets/92668715/def7126d-0db0-4409-98bd-6815a0e46cf7)

show_debug_message(steam_initialised()); returns true while all of the below returns false:
show_debug_message(steam_get_achievement("ACH_WELCOME_1"));
show_debug_message(steam_stats_ready());
show_debug_message(steam_is_overlay_enabled());
show_debug_message(steam_is_overlay_activated());

things to mention: 
1- i use a persistent object's step event to steam_update();
2- i am using steam version of gamemaker studio.
3- i have not released my game on steam yet, i am testing achievement stuff via gamemaker studio, as a project

**Comment by stuckie** [comment]
Thanks for reporting this issue, but in order to investigate we will need a small project which shows this issue. Please report this issue again, but ensure you have a suitable project open at the time and you have checked the “Include Project” option on the bug form.

**Comment by stuckie** [comment]
Alternatively, attach a project via Google Drive or something similar that we can request access for.

**Comment by kt-altyn** [comment]
> Alternatively, attach a project via Google Drive or something similar that we can request access for.

to make things simple, i created a new project and imported "steamworks ext", run the project and it stuck on "you are not logged in to steam!!" 

i guess i do not need to upload default project of the extension.

**Comment by kt-altyn** [comment]
i logged off from my yoyogames account then relogged in. didnt change anything at all and the problem is solved. i dont know how.
