### ISSUE TITLE
steam_request_global_stats never triggers

### ISSUE THREAD

**Issue by 1-800-thewolf** [YoYoGames/GMEXT-Steamworks#59]
I'm attempting to use the steam_request_global_stats function [as demonstrated in the documentation example](https://github.com/YoYoGames/GMEXT-Steamworks/wiki/achievements#steam_request_global_stats). steam_request_global_stats never triggers the async function, though.

steam_initialised returns **true**.
steam_stats_ready returns **true**.
steam_request_global_stats returns **true**
steam_get_stat_int returns **6** which is the correct value for 1 user but is not the **total aggregated value**.
The Steam Async event never triggers and I never see the _show_debug_message("{0}: {1}", _type, _success)_ report.

I've given it multiple hours and still never triggers the async event. Is there something different that needs to be done to successfully retrieve global stats?

**Comment by DiasFranciscoA** [comment]
Please let us know what version of the extension you are using as the last version was not yet published on the marketplace is just available from GitHub published releases.

**Comment by 1-800-thewolf** [comment]
@DiasFranciscoA oh good point! I'm using 1.6.0. Is this fixed in 1.6.1?

**Comment by 1-800-thewolf** [comment]
I just updated to 1.6.1 and still got the same result.

`steam_get_stat_int `results in **7** (which is correct)
`steam_get_global_stat` results in **0** (which is incorrect)

Again the Steam async event never triggers. I don't know what step I'm missing to correctly access the aggregate global stats.

**Comment by DiasFranciscoA** [comment]
Ensure that the statistic you’re attempting to query is marked as “aggregatable” within the Steam dashboard settings. Not all statistics can be queried for global stats; they must be specifically flagged on the server side through the Steam dashboard for such queries to be possible.

**Comment by 1-800-thewolf** [comment]
Good question, but the stat is definitely marked as aggregated:
![image](https://github.com/YoYoGames/GMEXT-Steamworks/assets/17304275/f7bd1964-86e9-46c1-a8d9-85c5ba1dca30)

I'm definitely also referencing the same stat name in my code and it still shows 0 for the global stat:
![image](https://github.com/YoYoGames/GMEXT-Steamworks/assets/17304275/1a789683-5bfd-4bca-b0a9-af0d5022a5d7)

I don't know if it matters, but steam_get_global_stat flags as wrong syntax. It says it takes no more than 0 arguments.

It also might not be obvious from the screenshot, but that version of the game is published and is what I'm using.

Is there some other initialization function I'm supposed to run or maybe a different setting in Steamworks? This is admittedly my first Steam game.

**Comment by 1-800-thewolf** [comment]
It looks like, according to Steam's documentation, we need to RequestCurrentStats before requesting global stats:
https://partner.steamgames.com/doc/api/ISteamUserStats#RequestGlobalStats

That might not be the issue, though, because it looks like the request is successful according to the Steam Async output.

**Comment by DiasFranciscoA** [comment]
We have just updated the Steamworks extension v1.6.2 to meet with Steamworks standards on global stats and achievements.
Please check this version as it will most likely solve your problem.

The old function `steam_get_global_stat` was removed in favor of `steam_get_global_stat_int` and `steam_get_global_stat_real` your global stat is marked as an integer so you should use the `steam_get_global_stat_int` as you do for non global stats.

Please close this issue if this solves your problem.

**Comment by 1-800-thewolf** [comment]
@DiasFranciscoA, you're my hero! It's indeed working beautifully. Thanks so much for putting so much work into getting this up and running.
