### ISSUE TITLE
User Authentication ISteamUser::GetAuthSessionTicket.

### ISSUE THREAD

**Issue by CelaldoganGunes** [YoYoGames/GMEXT-Steamworks#6]
First of all, please update Steamworks extension manual page about user auth methods

2ndly, I see that you added user auth methods, please add Session Tickets support, too.

If we use GameMaker as our game's server, we have 2 options: 
1st, write an extension with c++ to use steam_user_request_encrypted_app_ticket within server.
![image](https://user-images.githubusercontent.com/17123945/205733995-04de6c3e-fd49-4a2c-af04-68e9cdc83aa1.png)

2nd, we can use ISteamUser::GetAuthSessionTicket in client, then send the data we receive to server and use http_get method to verify player.
![image](https://user-images.githubusercontent.com/17123945/205734008-7c009e67-f2a4-45cd-bf8d-13a0bcc0b921.png)

Second option is more simple.
I edited YellowAfterLife's steamworks extension to use second option but if you add this method to official extension, i will use it. Currently using both official extension and YAL's one.

Because of this,
1) create an extension for servers that use steam api 
or 
2) add a new method to use ISteamUser::GetAuthSessionTicket method.

I can help with 2nd option. I can share my code that i added to YAL's extension. Please contact me if you need that but it is simple and your developers can do that easily.

**Comment by CelaldoganGunes** [comment]
https://partner.steamgames.com/doc/features/auth

**Comment by DiasFranciscoA** [comment]
Hi,

Thank you for reaching out to us with your request we have a new version released that already includes these functions.
Make sure you update to Runtime version 2023.1 (required).

I'll be closing this ticket now

**Comment by CelaldoganGunes** [comment]
I am sorry but the extension still doesn't have the function i told you about.
I said, you shold add ISteamUser::GetAuthSessionTicket

**Comment by CelaldoganGunes** [comment]
Thank you for adding this function. My game fully depends on it :)
