### ISSUE TITLE
YYprojectName variable in post_step_bat resolves to an empty string when using CLI for Linux

### ISSUE THREAD

**Issue by patchuby** [YoYoGames/GMEXT-Steamworks#61]
I'm building my game on Linux from Windows using CLI. The process fails to produce a zip because of Steamworks as far as I can tell. The variable YYprojectName seems to resolve to an empty string and in so giving the file path ".zip" instead of "[project_name].zip".

Here is the output :

```[STEAMWORKS] INIT: Script initialization succeeded (v1.6.2 :: 1).
"Copying Linux (64 bit) dependencies"


    Directory: C:\CDS-Builds\Linux


Mode                 LastWriteTime         Length Name                                                                 
----                 -------------         ------ ----                                                                 
d-----        08/03/2024     12:51                _temp                                                                


Expand-Archive : The path '.zip' either does not exist or is not a valid file system path.
At line:1 char:34
+ ... e = 'Stop'; Expand-Archive -Path $env:PS_SRCFILE -DestinationPath $en ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (.zip:String) [Expand-Archive], InvalidOperationException
    + FullyQualifiedErrorId : ArchiveCmdletPathNotFound,Expand-Archive
 
[STEAMWORKS] ERROR: Failed to extract contents of '.zip' to '_temp\'.


C:\GMS\extensions\Steamworks\post_build_step.bat exited with non-zero status (1)```

**Comment by DiasFranciscoA** [comment]
Extension scripts were changed to not relying on YYprojectName (updated in main repo, pending release and marketplace update)

**Comment by patchuby** [comment]
@DiasFranciscoA I've updated the post_step.bat/.sh from your yesterday commit but now I'm getting this when building for Mac YYC : 
```"Copying macOS (64 bit) dependencies"
Exception calling "GetUnresolvedProviderPathFromPSPath" with "1" argument(s): "Cannot find drive. A drive with the
name ' =_YYprojectName' does not exist."
At line:1 char:94
+ ...  $basePath; $ExecutionContext.SessionState.Path.GetUnresolvedProvider ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : DriveNotFoundException
```

**Comment by patchuby** [comment]
@DiasFranciscoA I noticed that the `_YYprojectName` error happened during cleaning but afterwards Steamworks extension scripts were not even called (couldn't see another `[STEAMWORKS]` in the output after cleaning). 

Cleaning seems to be broken in CLI so I cleaned in IDE and then launched the CLI to build and the error popped up in the build output.

Also noticed that the project I sent might have had Steamworks disabled for Ubuntu, double check if this is enabled on your side.

The issues I've reported the last few days all seem to be connected, let me know if you want me to create a new issue for this or comment on another issue (since this one is closed). I'm also available for a call on discord ("patchuby_") to go over details if you need
