### ISSUE TITLE
Add use of Channels for sending and receiving network packets

### ISSUE THREAD

**Issue by TheoryGeorgiou** [YoYoGames/GMEXT-Steamworks#64]
This is already a feature in the Steam API and would mean minor modification to simply add the optional nChannel parameter to the steam_net_packet_receive() and steam_net_packet_send() extension functions.

Currently without the parameter all packets are sent through channel 0 and are consumed by the first instance of a game not allowing sequent instances to receive the packet this makes testing on a single computer and steam account impossible. 

Adding the nChannel parameter would allow a channel to be designated for each open game client allowing easier testing.
This would also add support for instances networking, such as using deferent channel per room.

Here is a link to the steam docs referencing the nChannel
https://partner.steamgames.com/doc/api/ISteamNetworking

**Comment by TheoryGeorgiou** [comment]
I have done my best to resolve this issue using a fork. Here is the pull request though I am not a C++ dev so please inform of how to fix the issues in the pull request.

https://github.com/YoYoGames/GMEXT-Steamworks/pull/65

**Comment by jzavala-YYG** [comment]
"Merged" in this commit: ad7af527a644a6ca2dbdef50ebe5f440ad01b453

**Comment by YYBartT** [comment]
Updated the documentation in the source repo and updated the wiki as well.
