### ISSUE TITLE
steam_file_get_list() is marked as returning a struct, while it actually returns an array

### ISSUE THREAD

**Issue by DragoniteSpam** [YoYoGames/GMEXT-Steamworks#66]
[steam_file_get_list()](https://github.com/YoYoGames/GMEXT-Steamworks/wiki/cloud#steam_file_get_list) returns an array of structs, but the feather return type is "struct," which causes a GM1041 error when you try to use it

**Comment by DiasFranciscoA** [comment]
This is fixed in latest release 1.6.6
