### ISSUE TITLE
Add the "SDK Redistributables" to the releases instead of using the post_build_step scripts

### ISSUE THREAD

**Issue by shichen85** [YoYoGames/GMEXT-Steamworks#67]
According to Valve's [SDK Access Agreement](https://partner.steamgames.com/documentation/sdk_access_agreement#:~:text=(b)%20reproduce%20and%20distribute%20the%20part%20of%20the%20SDK%20provided%20inside%20the%20folder%20named%20redistributable_bin%20(the%20%22SDK%20Redistributables%22)%20along%20with%20the%20Licensee%20Software%20in%20object%20code%20form.), developers are free to distribute the "SDK Redistributables" in `redistributable_bin`. 

So rather than requiring the user to configure the SDK Path in the extension editor, which is prone to the user choosing the wrong SDK version or the wrong path, the released yymps could just add the "SDK Redistributables" to the extension as resource files. I believe this will make the integration of this extension smoother for the user and ensure that they are using the correct Steam SDK version.

**Comment by jackerley** [comment]
Hi @shichen85 in order to access the SDK, devs have to agree to the Steamworks SDK Access Agreement which is controlled by Valve, we can't add the binaries to a public git repo where devs who haven't made that agreement could access it. Sorry
