### ISSUE TITLE
Add item stack

### ISSUE THREAD

**Issue by Slmephi** [YoYoGames/GMEXT-Steamworks#68]
Please add a function to Stack items in the inventory

Thank you

**Comment by DiasFranciscoA** [comment]
Hello @Slmephi could you please be more specific on what you actually require or want to request to be added to the extension?
Please give an example or point to the Steamworks SDK documentation for the given feature.

**Comment by Slmephi** [comment]
Hello @DiasFranciscoA ,
When i drop items every item has a single place in the steam inventory. There is a possibility several games use in which they stack similar items. For example when i drop 20 Wood planks, then i have actual 20 items in the inventory with each an own spot and unique id. I would like to stack them to a single spot with a number as indicator for the value.

seperate items like they are now 
![image](https://github.com/YoYoGames/GMEXT-Steamworks/assets/171952100/bd5a7dbd-d076-48fd-b8fa-4b72903b5cc0)

i would like this 
![image](https://github.com/YoYoGames/GMEXT-Steamworks/assets/171952100/4d1074a8-6c0c-4de2-a534-d7671db99521)

**Comment by DiasFranciscoA** [comment]
are you following the documentation they provide under [Inventory Schema](https://partner.steamgames.com/doc/features/inventory/schema), there is a stack option there

**Comment by Slmephi** [comment]
Yes i saw it but it dows not work, when i set it to true the items do not stack automatically. Actually i need to use the web api to do this because the extension does not have the function yet

**Comment by DiasFranciscoA** [comment]
Hello again @Slmephi, what would be the function that you want to be added? 
What is the web api call you are using?

**Comment by Slmephi** [comment]
Hello @DiasFranciscoA 
<html>
<body>
<h2 class="bb_section" style="color: white; font-family: &quot;Motiva Sans&quot;, sans-serif; font-weight: 300; font-size: 22px; margin: 40px 0px 6px; line-height: 1.5em; border-bottom: 1px solid rgba(255, 255, 255, 0.2); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(22, 25, 32); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Consolidate</h2><div class="bb_code http hljs" style="display: block; overflow-x: auto; padding: 12px; background: rgba(35, 35, 35, 0.6); color: rgb(230, 225, 220); border: 1px solid rgb(83, 83, 84); border-radius: 3px; margin: 8px; font-size: 12px; font-family: Consolas, monospace; white-space: pre-wrap; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><span class="hljs-attribute" style="color: rgb(205, 168, 105);">POST https://partner.steam-api.com/IInventoryService/Consolidate/v1/</span></div>
Name | Type | Required | Beschreibung
-- | -- | -- | --
key | string | ✔ | Steamworks Web API publisher authentication key.
appid | uint32 | ✔ |  
steamid | uint64 | ✔ |  
itemdefid | uint64 array | ✔ |  
force | bool |   |  

<br style="color: rgb(172, 181, 190); font-family: &quot;Motiva Sans&quot;, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(22, 25, 32); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><span style="color: rgb(172, 181, 190); font-family: &quot;Motiva Sans&quot;, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(22, 25, 32); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;">Consolidate items of the given type within an user's inventory.</span><br style="color: rgb(172, 181, 190); font-family: &quot;Motiva Sans&quot;, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(22, 25, 32); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><br style="color: rgb(172, 181, 190); font-family: &quot;Motiva Sans&quot;, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(22, 25, 32); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><span style="color: rgb(172, 181, 190); font-family: &quot;Motiva Sans&quot;, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(22, 25, 32); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;">Whenever items are combined into a stack, the resulting stack takes the market and trade restriction values of the most-restricted item. The Consolidate action ignores any item with an active market or trade restriction, unless 'force' is set to true.</span><br style="color: rgb(172, 181, 190); font-family: &quot;Motiva Sans&quot;, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(22, 25, 32); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><br style="color: rgb(172, 181, 190); font-family: &quot;Motiva Sans&quot;, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(22, 25, 32); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><strong style="color: rgb(221, 221, 221); font-family: &quot;Motiva Sans&quot;, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(22, 25, 32); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">NOTE:</strong><span style="color: rgb(172, 181, 190); font-family: &quot;Motiva Sans&quot;, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(22, 25, 32); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;"><span> </span>This call requires a publisher API key to use this method. As such this API<span> </span></span><strong style="color: rgb(221, 221, 221); font-family: &quot;Motiva Sans&quot;, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(22, 25, 32); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">MUST</strong><span style="color: rgb(172, 181, 190); font-family: &quot;Motiva Sans&quot;, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(22, 25, 32); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;"><span> </span>be called from a secure server, and can never be used directly by clients!</span>
</body>
</html>

**Comment by DiasFranciscoA** [comment]
Okay so if you set the itemdef `auto_stack : true` to will make the item auto stack correctly notice though that previously generated items will not stack only item granted after the auto_stack property was set to true.

Here is a workflow example:

* Consume all your items using a combination of `steam_inventory_get_all_items()` and `steam_inventory_consume_item()`
* Now make sure your coin item is set to `auto_stack: true` (ie.: upload a new itemdef json file)
* Use the `steam_inventory_generate_items([{ item_def: 1, quantity: 5 }]);` to award yourself with 5 coins
* Use steam_inventory_get_all_items() again to list the items you have you should see that you have stacked items

![image](https://github.com/YoYoGames/GMEXT-Steamworks/assets/85873067/d3512901-1530-448a-bfde-3946b22ba513)

Above is an image of the output that we obtained locally.

**Comment by Slmephi** [comment]
Hi, yes it works with a steam_inventory_generate_items([{ item_def: 1, quantity: 5 }]); function but only because you generate 5 at once. This function is only available for developers and not usable ingame later.
With the item trigger function you use ingame for release with the playtime generators  it does not work or i didn't got it to work

**Comment by Slmephi** [comment]
But all over, if its to compolicated i use the web api for this, because i only need the steam id of the user this is a function people can't really cheat and its still easy to implement also when i would prefer to use only the extension =)

**Comment by DiasFranciscoA** [comment]
That is really odd because if you use the `steam_inventory_generate_items([{ item_def: 1, quantity: 5 }]);` and call it 10 times you still get a stacked inventory. So if that's really not the case with the `playtime generators` that might be a misconfiguration or Steamworks limitation (which I doubt).

**Comment by Slmephi** [comment]
Yes, i don't know why, when i use the generate fucntion or the web API the stacking works well but when i use the trigger function it does not work

**Comment by DiasFranciscoA** [comment]
The SDK API doesn't even have the [Consolidate](https://partner.steamgames.com/doc/webapi/IInventoryService#Consolidate) function in it or anything similar, we have already contacted the Steamworks team on this topic and will wait for an answer from them. It might be that it is indeed a limitation OR a more up-to-date SDK version is required (which we don't support at the moment)

**Comment by Slmephi** [comment]
ok, thank you for the intense investigation =)

**Comment by DiasFranciscoA** [comment]
This can be done and apparently must be done using the function [steam_inventory_transfer_item_quantity](https://github.com/YoYoGames/GMEXT-Steamworks/wiki/inventory#steam_inventory_transfer_item_quantity).
