### ISSUE TITLE
Problem with item exchange

### ISSUE THREAD

**Issue by Slmephi** [YoYoGames/GMEXT-Steamworks#69]
Hello, i have a problem with the item exchange function,
I setup an item with defid 1 : goldcoin
I setup an item  with defid 1000: Upgrade Symbol.
The upgradesymbol has an exchange recept with 1 x 10 so 10 times goldcoin needed.

Now i get the unique item ID and create an item exchange function.
In this i have the unique item ID with an quantity of 10 in the destroy and the itemdefid 1000 with a quantity of 1 in the create array.
When i now trigger the function i always get back an failed Response.

I also tried to Stack the items before with the Web API and to change both quantities to 1 only,... and i tried to take 10 times 1 goldcoin with 10 unique def ids instad of 10 in 1 Stack,....

I always get an failed Response.

Greetings

**Comment by Slmephi** [comment]
var _arrayDestroy = [
    { item_id: global.array_gold_coin[0], quantity: 10 }
];
var _arrayCreate = [
    { item_def: 1000, quantity: 1 }
];
handle = steam_inventory_exchange_items(_arrayCreate, _arrayDestroy);

in global.array_gold_coin[0] is the unique item instance id (for example: 4777710153766753113) of the itemdef 1
item_def: 1000 is the item i want to drop
itemdef 1 is stacked with webapi
in itemdef 1000 i have the exchange code:  "exchange": "1x10",

i also tried this without the items stacked:

var _arrayDestroy = [
    { item_id: global.array_gold_coin[0], quantity: 1 },
    { item_id: global.array_gold_coin[1], quantity: 1 },
    { item_id: global.array_gold_coin[2], quantity: 1 },
    { item_id: global.array_gold_coin[3], quantity: 1 },
    { item_id: global.array_gold_coin[4], quantity: 1 },
    { item_id: global.array_gold_coin[5], quantity: 1 },
    { item_id: global.array_gold_coin[6], quantity: 1 },
    { item_id: global.array_gold_coin[7], quantity: 1 },
    { item_id: global.array_gold_coin[8], quantity: 1 },
    { item_id: global.array_gold_coin[9], quantity: 1 }
];
var _arrayCreate = [
    { item_def: 1000, quantity: 1 }
];
handle = steam_inventory_exchange_items(_arrayCreate, _arrayDestroy);

in global.array_gold_coin[0]-global.array_gold_coin[9] are the unique item instance ids (for example: 4777710153766753113) of the itemdef 1 items in the inventory i read them out with steam_inventory_get_all_items(); and saved all itemids of this in the array
item_def: 1000 is the item i want to drop
in itemdef 1000 i have the exchange code:  "exchange": "1x10",


both versions always bring the error taht it failed but i don't know why, tried around since hours, and read out all variables, in them are the correct values

**Comment by Slmephi** [comment]
The item definition i want to destroy

{
  "appid": "XXXXXX",
  "itemdefid": "1",
  "Timestamp": "2024-06-06T17:17:33Z",
  "modified": "20240606T171733Z",
  "date_created": "20240602T184431Z",
  "type": "item",
  "display_type": "",
  "name": "GOLD COIN",
  "quantity": 1,
  "description": "A gold coin, used for crafting and updates",
  "background_color": "FFFF33",
  "icon_url": "XXXXX",
  "icon_url_large": "XXXXX",
  "name_color": "000000",
  "tags": "currency:gold",
  "tradable": false,
  "marketable": false,
  "commodity": true,
  "store_hidden": true,
  "auto_stack": true,
  "granted_manually": true,
  "item_quality": "1"
}


The item definition which i want create

{
  "appid": "XXXXXXX",
  "itemdefid": "1000",
  "Timestamp": "2024-06-06T17:48:24Z",
  "modified": "20240606T174824Z",
  "date_created": "20240605T182210Z",
  "type": "item",
  "display_type": "",
  "name": "DIG TIME UPGRADE",
  "quantity": 1,
  "description": "A dig time upgrade symbol",
  "background_color": "FFFF33",
  "icon_url": "XXXXX",
  "icon_url_large": "XXXXX",
  "name_color": "000000",
  "exchange": "1x10",
  "tradable": false,
  "marketable": false,
  "commodity": true,
  "store_hidden": true
}

**Comment by Slmephi** [comment]
@stuckie 
Hi, how can i send a small project.
to get the items you need to have the game in the steam library and have access to the admin functions for it. i have a small project here but if i add it it will not work, thats why i send here the necessary code an item definitions. how can i send a new request with a working project to test.
sry that i wrote here but didn't wanted to spam the requests full with questions what exact you need.

greetings

**Comment by stuckie** [comment]
You can still submit the project with the above put in, in the right places, as it saves us some time in trying to recreate the same project.. if we need further access, we can get in contact with you when the bug gets assigned.
