### ISSUE TITLE
steam_inventory_exchange_items does not work

### ISSUE THREAD

**Issue by Slmephi** [YoYoGames/GMEXT-Steamworks#70]
Hello,
steam_inventory_exchange_items(create_arr, destroy_arr) does not work,
I dropped several items which i want to exchange against another but the function always sends me an not successful message and it does not do anything.

[treasure hunter.zip](https://github.com/user-attachments/files/15743892/treasure.hunter.zip)

**Comment by DiasFranciscoA** [comment]
This should now be fixed in version 1.6.8 (thank you for reaching out)

**Comment by Slmephi** [comment]
works now, thank you =)

**Comment by Slmephi** [comment]
Hi, i have another question to this function.
The function itself works now without problems but there is something confusing.

in you documentation is written this code :
var _arrayDestroy = [
    { item_id: player.cursed_sword, quantity: 1 },
    { item_id: player.apple, quantity: 7 },
];

var _arrayCreate = [
    { item_def: global.holy_sword, quantity: 1 },
    { item_def: global.orange, quantity: 2 }
];

steam_inventory_exchange_items(_arrayCreate, _arrayDestroy);

and this description:
Given the provided items to be destroyed and the items to be create the code above will perform an exchange removing the current items (arrayDestroy) from the inventory and adding the new (arrayCreate) in their place. 


which shows to exchange several items against other several items.

But in the steam documentation of the api is written:
The caller of this API passes in the requested item and an array of existing items and quantities to exchange for it. The API currently takes an array of items to generate but at this time the size of that array must be 1 and the quantity of the new item must be 1.

Which says that actually its not possible to exchange items against several items. The create array is only allowed to have 1 item with quantity 1
