### ISSUE TITLE
extension documentation for steam_inventory_exchange_items wrong?

### ISSUE THREAD

**Issue by Slmephi** [YoYoGames/GMEXT-Steamworks#71]
Hello,

in your documentation is written this code :
var _arrayDestroy = [
{ item_id: player.cursed_sword, quantity: 1 },
{ item_id: player.apple, quantity: 7 },
];

var _arrayCreate = [
{ item_def: global.holy_sword, quantity: 1 },
{ item_def: global.orange, quantity: 2 }
];

steam_inventory_exchange_items(_arrayCreate, _arrayDestroy);

and this description:
Given the provided items to be destroyed and the items to be create the code above will perform an exchange removing the current items (arrayDestroy) from the inventory and adding the new (arrayCreate) in their place.

which shows to exchange several items against other several items.

But in the steam documentation of the api is written:
https://partner.steamgames.com/doc/api/ISteamInventory#ExchangeItems
The caller of this API passes in the requested item and an array of existing items and quantities to exchange for it. The API currently takes an array of items to generate but at this time the size of that array must be 1 and the quantity of the new item must be 1.

Which says that actually its not possible to exchange items against several items. The create array is only allowed to have 1 item with quantity 1

**Comment by Slmephi** [comment]
i tried it now and the extension deocumentation is wrong.

When i try to create items more then 1 for exampple:

var _arrayCreate = [
    { item_def: 1, quantity:10}
];

there is dropping nothing and i also don't get a async answer

When i try to drop a list of items with always 1, for example:
var _arrayCreate = [
{ 
item_def: 1, quantity:1,
item_def: 2, quantity:1,
item_def: 3, quantity:1,
item_def: 4, quantity:1
}
];

then it only drops the first item and ignores the others.
That means that the steamworks documentation is correct that it must be 1 and only drops 1 item also when a list is allowed.

The only correct working version is:

var _arrayCreate = [
    { item_def: 1, quantity:1}
];

Here is only 1 item and quantity 1

**Comment by DiasFranciscoA** [comment]
Fixed in: 7d1e9671b3a65bb143eac16d17e52e72c6300313
