### ISSUE TITLE
extension documentation for steam_inventory_transfer_item_quantity is wrong?

### ISSUE THREAD

**Issue by Slmephi** [YoYoGames/GMEXT-Steamworks#72]
Hello, 
You give in the documentation this example:
handle = steam_inventory_transfer_item_quantity(global.apple, 2, global.oranges);

and this information:
The above code will trigger a transfer between two items owned by the user the amount to be transferred in the example, the user will lose 2 apples and receive 2 oranges.

This means you write here you can change one item into another.

but in the steam inventory api documentation si written:
https://partner.steamgames.com/doc/api/ISteamInventory#TransferItemQuantity
This can be used to stack, split, and moving items. The source and destination items must have the same itemdef id.

That means you cannot change an apple into an orange, you can only make 2 or more stacks of apples and transfer them between the stacks.

greetings

**Comment by DiasFranciscoA** [comment]
Fixed in: 7d1e9671b3a65bb143eac16d17e52e72c6300313
