### ISSUE TITLE
Game fails to launch around 25-30% of the time

### ISSUE THREAD

**Issue by dynamic-zero** [YoYoGames/GMEXT-Steamworks#8]
When launching the product on Steam the game fails to launch consistently. Steam thinks the game is running but it is not visible in task manager. Stopping and starting the game several times on Steam it opens eventually.

IDE Version 2022.11.1.56
Runtime 2022.11.1.75

Steam extension version 1.1.5
Steamworks SDK version 1.55

**Comment by KingJavo** [comment]
I'm getting the same issue.

IDE Version 2022.11.1.56
Runtime 2022.11.1.75

Steam extension version 1.0.0
Steamworks SDK version 1.55

**Comment by CelaldoganGunes** [comment]
I am not the developer of the extension but i think you should post your output logs here.It would make the process faster.
![image](https://user-images.githubusercontent.com/17123945/210719914-f75c1d26-651f-4c97-b191-3deeffa86b3c.png)

**Comment by YellowAfterlife** [comment]
Not a whole lot in that log (captured by adding Launch Options) in steam game properties
```
Setting scheduler resolution to 1
Create Error Form

***************************************
*     YoYo Games Runner v2022.11(1)[r75]    *
***************************************	 
RunnerLoadGame: C:\Program Files (x86)\Steam\steamapps\common\Nuclear Throne\data.win
#########################################################################
####!!!!$$$$$$ pwd - C:\Program Files (x86)\Steam\steamapps\common\Nuclear Throne\
#########################################################################
RunnerLoadGame() - C:\Program Files (x86)\Steam\steamapps\common\Nuclear Throne\data.win
YYG Game launching. Game file: C:\Program Files (x86)\Steam\steamapps\common\Nuclear Throne\data.win
Checking if INIFile exists at C:\Program Files (x86)\Steam\steamapps\common\Nuclear Throne/options.ini
INIFile C:\Program Files (x86)\Steam\steamapps\common\Nuclear Throne/options.ini Exists, loading....
Reading File C:\Program Files (x86)\Steam\steamapps\common\Nuclear Throne\data.win
Loaded File C:\Program Files (x86)\Steam\steamapps\common\Nuclear Throne\data.win(104903474)
IFF wad found
Get Resolution
Get Header Information
InitGMLFunctions
HighScore..SavePrePend = C:\Users\User\AppData\Local\nuclearthrone\
Game..Math..Graphic..Action..File..Resource..Interaction..3D..Particle..Misc..Time..DS..Sound..Physics..Gamepad..Buffers..Networking..Shaders..YoYo..Multiplayer..Fini

```so it makes it past the first chunk and then gets lost somewhere on the way.

**Comment by DiasFranciscoA** [comment]
This issue is now solved in the latest published version and latest marketplace version.
Please note that the required runtime version is 2023.1 now.
I'll be closing this issue now.
