### ISSUE TITLE
Add a binary/buffer/file version of steam_file_read

### ISSUE THREAD

**Issue by DragoniteSpam** [YoYoGames/GMEXT-Steamworks#81]
When writing steam cloud files, we have `steam_file_write` for writing text and `steam_file_write_file` to write the contents of an existing files.

When reading files, `steam_file_read` returns the contents of a file as text, but we don't have an equivalent for binary.

I'm not sure if we're supposed to use functions like `steam_get_local_file_change` to manually clone cloud save files to local storage instead, but since my save files are a mixture of plain text and binary data it would be super helpful to just have a version of `steam_file_read` that returns a buffer or something.

**Comment by DiasFranciscoA** [comment]
This feature was now merged and is available thanks to @nkrapivin contribution.
