### ISSUE TITLE
The presence of `steam_appid.txt` in the app's installation directory causes the app not to start the Steam client

### ISSUE THREAD

**Issue by shichen85** [YoYoGames/GMEXT-Steamworks#82]
I believe previous implementations of this extension writes a `steam_appid.txt` file to the app's installation directory. The current version `v1.6.9` is no longer doing that, but if that file is present, opening the *.exe file does not start the Steam client if the client is not started.

Replication steps:

1. In the GameMaker IDE, set the extension's `debug` setting to `auto`
2. Make a windows export with this extension
3. With Steam client closed, launch the *.exe file, see that it correctly launches the Steam client
4. Close the Steam client, add a `steam_appid.txt` file to the *.exe's directory with the same application ID that was set in the extension
5. Launch the *.exe file again, see that it does not launch the Steam client

This is problematic for published games that once used the old extension, because the old extension wrote the `steam_appid.txt` file to the user's directory. Unless the user completely uninstall the game and reinstall it, the `steam_appid.txt` file will not be removed during regular app update. With the `steam_appid.txt` file present, if the user is able to launch the game by directly launching the *.exe file with Steam client closed, they will get into an unintended state with the Steam SDK not initialized.

**Comment by DiasFranciscoA** [comment]
This is indeed an issue but one that we cannot control.

We are calling `SteamAPI_RestartAppIfNecessary()` which should handle the check to see if the current app requires a restart or not (is it been run from within the steam client or not). This function is being called correctly, but apparently it returns `false` (no need to restart) if there is a steam_appid.txt file in the game folder. This is a problem in the Steam SDK API itself. The C++ code is compliant with the guide lines given by Steam.

**Comment by DiasFranciscoA** [comment]
BTW, how do users end up with the steam_appid.txt file in their folders? this file should only exist if you are running from IDE or in debug mode... as Steam explains a game should never create this file... and this file is only intended to exist IF the game it being developed and needs to run without the client 🤔 if I create a release in GameMaker extract the zip and run the EXE from there no `steam_appid.txt` file is created... as expected.

**Comment by DiasFranciscoA** [comment]
EDIT: the change I see possible here is to make sure we delete the file before hand, as it shouldn't exist.

**Comment by shichen85** [comment]
> btw, how do users end up with the steam_appid.txt file in their folders? this file should only exist if you are running from IDE or in debug mode... as Steam explains a game should never create this file... and this file is only intended to exist IF the game it being developed and needs to run without the client 🤔 if I create a release in GameMaker extract the zip and run the EXE from there no `steam_appid.txt` file is created... as expected.

I have no idea why the file ended up in there, but I checked a few other GM games such as Rivals of Aether and Hyper Light Drifter, and their fresh install both have the text file in there.

**Comment by DiasFranciscoA** [comment]
This is now up and done :D a new version was just pushed, no release package just yet though. Will be in a couple minutes
