### ISSUE TITLE
Doesn't work steam_set_achievement steam_get_achievement steam_is_screenshot_requested()

### ISSUE THREAD

**Issue by mbeytekin** [YoYoGames/GMEXT-Steamworks#83]
My game is currently in the 'coming soon' phase on Steam, and I can play it through Steam. However, the problem is that none of the functions steam_set_achievement, steam_get_achievement, and steam_is_screenshot_requested() work. But, for example:

  if steam_is_screenshot_requested() ||  keyboard_check_pressed(vk_f11)
  {
      if(!directory_exists("screenshots")) {
          directory_create("screenshots");
      }
      var file = "screenshots\\mf" + string(irandom(10000000)) + ".png";
      screen_save(file)
      steam_send_screenshot(file, window_get_width(), window_get_height());
  }

When I do it this way, pressing the F11 key actually sends the screenshot to Steam. However, the steam_set_achievement function does not work at all. I am using version 1.6.9.

**Comment by jzavala-YYG** [comment]
@mbeytekin I can confirm that **_steam_set_achievement_** and **_steam_get_achievement_** are working properly. Probably you seen something that I don't, can you be more specific? 

about **_steam_is_screenshot_requested()_** I can't see it return in **_true_** code side seems good, I will try again while you let me know the exactly issues the the other 2 functions

Regards

**Comment by mbeytekin** [comment]
I'm so sorry. The issue with the object running the steam_update() function has been resolved now.
