### ISSUE TITLE
Section Setup Guide (IDE/Runtime 2022.6+) is outdated

### ISSUE THREAD

**Issue by Slmephi** [YoYoGames/GMEXT-Steamworks#85]
In the Guide the section [Setup Guide (IDE/Runtime 2022.6+)](https://github.com/YoYoGames/GMEXT-Steamworks/wiki/guides) is outdated, it should be renewed because the options look different and some options are not covered in this guide.

This is a picture how it looks in GITHUB and in the included files:
![image](https://github.com/user-attachments/assets/6fdae16e-b3ab-47c2-b84f-82628b1afc2e)

This is how it really looks in GameMaker:
![image](https://github.com/user-attachments/assets/bfc88aa4-9738-42fa-850c-15d1324904c1)

Changed:
- The design
- Debug Mode has now a dropdown with Enabled and Auto instead of a true checkbox
- The Log Level came new which is not covered in this guide

**Comment by DiasFranciscoA** [comment]
Fixed in commit: f3c149c18bd48ede76db0b7463efdf5b0c5f5fb4
Will be present in the next release
