### ISSUE TITLE
(Mac) When I disable the extention to create a Steam-free version it's still trying to run post_build_step.sh

### ISSUE THREAD

**Issue by ajrdesign** [YoYoGames/GMEXT-Steamworks#9]
I'm trying to compile my game without steamworks integrated for other platforms but when I try to package the game on Mac with all the "Copies to:" options unchecked it gives me the error:

The specified steamworks SDK path doesn't exist please edit the file 'post_build_step.sh' in your project's root folder

Why is it trying to run this if steamworks isn't supposed to be integrated?

**Comment by DiasFranciscoA** [comment]
Hi,

Please make sure you are using the latest version of the extension that message is from a previous version of the extension. Also make sure that you don't have script in the project root folder (next to the .yyp file) the script files in the new versions are included in the extension folder. So if you have any bat or sh files in the root folder please removed them and try again.

**Comment by DiasFranciscoA** [comment]
Hello, @ajrdesign can you confirm if the above comment solved your problem?

**Comment by DiasFranciscoA** [comment]
The bug will be closed as a result of inactivity, as we were unable to replicate it in newer versions of the extension.
